language: python
python:
  - '3.6'
install:
  - pip install tox
  - pip install travis-tox
  - pip install -e .
script:
  - pip uninstall setuptools -y && pip install 'setuptools>34.0' --ignore-installed # needed for updated version of html5lib
  - tox --skip-missing-interpreters
after_success:
  - coverage report
  - coveralls
